#!/usr/bin/env python3
"""Generate the consumer-scoped contracts from a real public/shared payload.

The all-surfaces contracts (contracts/openapi/marvisx.json,
contracts/actions/manifest.yaml) describe the full marvisx engine including
SaaS-only modules the public/shared projection deliberately excludes
(newsletter, hosted account, gui events, and file shares). Retired integration
tombstones are shared compatibility code and remain in the projection. OSS and
Enterprise consumers receive the projection payload, so their binding contract
must describe exactly what that payload serves.

The consumer artifacts are therefore DERIVED FROM THE PAYLOAD itself:

- contracts/openapi/marvisx-public-shared.json is the serialized
  ``app.openapi()`` of the payload's own runtime (the SaaS routers are
  absent, so the app boots without them — main.py imports them optionally);
- contracts/actions/manifest.public-shared.yaml is the all-surfaces manifest
  filtered to the domains whose use_cases module exists in the payload;
- contracts/openapi/VERSION-public-shared pins the derived set.

No Cloud/SaaS/private code is imported to make the contracts match: the
payload's contents are the single source of truth. One artifact set serves
OSS and Enterprise identically (they consume the same payload).

Determinism: same rules as contracts/openapi/generate.py — the workspace-root
default is pinned before the app import and the spec is serialized with
sort_keys. Regenerate only from a clean exact-SHA export of this repository.

Usage:
  python contracts/openapi/generate_consumer.py --payload <export-root>/payload
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
SPEC_OUT = REPO_ROOT / "contracts" / "openapi" / "marvisx-public-shared.json"
ACTIONS_OUT = REPO_ROOT / "contracts" / "actions" / "manifest.public-shared.yaml"
VERSION_OUT = REPO_ROOT / "contracts" / "openapi" / "VERSION-public-shared"

CONSUMER_SPEC_HEADER = (
    "# Governed consumer-scoped action manifest — public/shared payload.\n"
    "# GENERATED by contracts/openapi/generate_consumer.py from a real\n"
    "# exact-SHA export payload: domains whose use_cases module is absent\n"
    "# from the payload (e.g. file_shares) are removed; everything else is\n"
    "# carried over unchanged from contracts/actions/manifest.yaml.\n"
    "# Identical for OSS and Enterprise. Do not hand-edit.\n"
)


def _serialize_spec(spec: dict) -> str:
    return json.dumps(spec, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def build_consumer_spec(payload: Path) -> dict:
    """Import the payload's own app and return its OpenAPI spec.

    The SaaS-only routers are missing from the payload, and core/api/main.py
    imports them optionally, so the imported app advertises exactly the
    routes the payload can serve.
    """
    # Must be set before core.api is imported (machine-independence contract,
    # see contracts/openapi/generate.py).
    os.environ["MARVIS_WORKSPACE_ROOT"] = "/workspace"
    payload_root = str(payload.resolve())
    if payload_root not in sys.path:
        sys.path.insert(0, payload_root)
    from core.api.main import app  # noqa: PLC0415 — deferred by design

    return app.openapi()


def build_consumer_manifest(payload: Path) -> dict:
    """Filter the payload's all-surfaces manifest to payload-present modules."""
    manifest_path = payload / "contracts" / "actions" / "manifest.yaml"
    manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(manifest, dict) or not isinstance(manifest.get("domains"), dict):
        raise SystemExit(f"invalid all-surfaces manifest in payload: {manifest_path}")
    dropped = [
        domain
        for domain, entry in manifest["domains"].items()
        if not (payload / entry["module"]).exists()
    ]
    for domain in dropped:
        del manifest["domains"][domain]
    manifest["excluded_domains"] = sorted(dropped)
    return manifest


def _write_version(spec: dict, manifest: dict) -> None:
    lines = [
        "# Governed consumer-scoped contract pin — public/shared payload.",
        "# Generated by contracts/openapi/generate_consumer.py from a real",
        "# exact-SHA export payload; identical for OSS and Enterprise.",
        "schema: marvis-consumer-contract/v1",
        'scope: "public-shared"',
        f'openapi: "{spec["openapi"]}"',
        f"paths: {len(spec['paths'])}",
        "generator: contracts/openapi/generate_consumer.py",
        "source_contract: contracts/openapi/marvisx.json",
        "action_manifest: contracts/actions/manifest.public-shared.yaml",
        f"action_domains: {len(manifest['domains'])}",
    ]
    VERSION_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--payload",
        type=Path,
        required=True,
        help="payload/ directory of a clean exact-SHA export of this repository",
    )
    args = parser.parse_args(argv)
    payload = args.payload.resolve()
    if not (payload / "contracts" / "openapi" / "marvisx.json").is_file():
        raise SystemExit("payload does not carry the all-surfaces contract")

    spec = build_consumer_spec(payload)
    SPEC_OUT.write_text(_serialize_spec(spec), encoding="utf-8")

    manifest = build_consumer_manifest(payload)
    ACTIONS_OUT.write_text(
        CONSUMER_SPEC_HEADER
        + yaml.safe_dump(manifest, sort_keys=True, allow_unicode=True),
        encoding="utf-8",
    )

    _write_version(spec, manifest)
    print(
        f"wrote {SPEC_OUT.relative_to(REPO_ROOT)} — paths {len(spec['paths'])} | "
        f"action domains {len(manifest['domains'])} | "
        f"excluded {manifest['excluded_domains']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
